# Eigen Decomposition of a Matrix

In [60]:
# import the necessary libraries
import numpy as np

The formula for eigen decomposition is A=QΛQ**(-1)

In [61]:
# take a sample matrix
A = np.array([[4,2],[-5,-3]])
A

array([[ 4,  2],
       [-5, -3]])

In [62]:
#find the eigen values and vectors of the matrix
lambdas, V = np.linalg.eig(A)

In [63]:
#find the inverse of the matrix
V_inv = np.linalg.inv(V)

In [64]:
#make the lambda values into a diagonal matrix
L = np.diag(lambdas)

In [65]:
#check to see if we get back the sample matrix
np.dot(np.dot(V,L),V_inv)

array([[ 4.,  2.],
       [-5., -3.]])

Eigen Decomposition of a symmetric matrix
A=QΛQ**(-1) = QΛQ(T)

In [66]:
#take a symmetric matrix
A2 = np.array([[2,1],[1,2]])
A2

array([[2, 1],
       [1, 2]])

In [67]:
#find the eigen values and vectors of the matrix
lambdas2 , V2 = np.linalg.eig(A2)

In [68]:
# find the inverse of the matrix
V2_inv = np.linalg.inv(V2)
V2_inv

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [69]:
#create a diagonal matrix with the eigen values
L2 = np.diag(lambdas2)

In [70]:
# check to see if we get back the symmetric matrix
np.dot(np.dot(V2,L2),V2_inv)

array([[2., 1.],
       [1., 2.]])

In [71]:
# check to see if we get back the symmetrix matrix by replacing the inverse with the transpose
np.dot(np.dot(V2,L2),V2.T)

array([[2., 1.],
       [1., 2.]])

This proves that for any symmteric matrix, the decomposed vector Q will be orthogonal because Q.Q-transpose is equal to an Identity matrix I

In [72]:
#condition to check if the eigen vector's transpose is orthogonal
np.dot(V2,V2.T)

array([[1., 0.],
       [0., 1.]])

In [73]:
#condition to check if the eigen vector and its inverse are orthogonal
np.dot(V2,V2_inv)

array([[1., 0.],
       [0., 1.]])