# Moore-Penrose Pseudoinverse

#### The Moore-Penrose pseudoinverse is widely used in fields where you need to solve systems of linear equations or deal with matrices that are not square or invertible. It provides an approximate solution when an exact one isn’t possible.

In [6]:
#Import all the important libraries
import numpy as np

The moore penrose pseudoinverse is given by the formula

A+ = V*Σ+*U^T

In [7]:
#take a sample matrix A
A = np.array([[-1,2],[3,-2],[5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [8]:
#SVD of A
U,d,VT = np.linalg.svd(A)
U,d,VT

(array([[ 0.12708324,  0.47409506,  0.87125411],
        [ 0.00164602, -0.87847553,  0.47778451],
        [ 0.99189069, -0.0592843 , -0.11241989]]),
 array([8.66918448, 4.10429538]),
 array([[ 0.55798885,  0.82984845],
        [-0.82984845,  0.55798885]]))

The sigma+ matrix is calculate by taking the reciprocal of the singular values from SVD (which is done using the inverse method) and matching its dimensions to the input matrix A and then taking its transpose

In [19]:
d_plus = np.diag(d)
d_plus_new = np.linalg.inv(d_plus)
d_plus_new

array([[0.1153511 , 0.        ],
       [0.        , 0.24364718]])

In [26]:
#taking the transpose
Σ = np.concatenate([d_plus_new,[[0,0]]])
Σ.T

array([[0.1153511 , 0.        , 0.        ],
       [0.        , 0.24364718, 0.        ]])

In [29]:
#the pseudo-inverse is calculated using the formula and numpy dot product
np.dot(VT.T,np.dot(Σ.T,U.T))

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])

To verify the correctness of the matrix, we use numpy's inbuilt pseudoinverse function

In [28]:
np.linalg.pinv(A)

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])