# Singular Value Decomposition

Unlike Spectral decomposition/Eigen decomposition which only work on square matrices, Singular value decomposition works on matrices of any shape (rectangular, square etc.)
<br> <br>
It breaks it down into a left singular matrix, singular value diagonal matrix and right singular value matrix
<br>
<br>
A=UΣV^T

In [218]:
#import the necessary libraries
import numpy as np

In [210]:
#initialize a sample rectangular matrix
A = np.array([[2,1],[3,1]])
A

array([[2, 1],
       [3, 1]])

In [211]:
#to apply singular value decomposition
U,d,VT = np.linalg.svd(A)
U,d,VT

(array([[-0.57604844, -0.81741556],
        [-0.81741556,  0.57604844]]),
 array([3.86432845, 0.25877718]),
 array([[-0.93272184, -0.36059668],
        [ 0.36059668, -0.93272184]]))

In [212]:
#construct a diagonal matrix
d = np.diag(d)
d

array([[3.86432845, 0.        ],
       [0.        , 0.25877718]])

In [213]:
#reconstruct the original matrix using the svd formula
np.dot(U,np.dot(d,VT))

array([[2., 1.],
       [3., 1.]])

## if the input matrix is not a square matrix

In [214]:
A = np.array([[-1,2],[3,-2],[5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [215]:
#to apply singular value decomposition
U,d,VT = np.linalg.svd(A)
U,d,VT

(array([[ 0.12708324,  0.47409506,  0.87125411],
        [ 0.00164602, -0.87847553,  0.47778451],
        [ 0.99189069, -0.0592843 , -0.11241989]]),
 array([8.66918448, 4.10429538]),
 array([[ 0.55798885,  0.82984845],
        [-0.82984845,  0.55798885]]))

In [216]:
#construct a diagonal matrix with the same dimensions as the matrix that you are trying to reconstruct
dia = np.diag(d)

S = np.concatenate([dia,[[0,0]]],axis = 0)

In [219]:
#reconstruct the original matrix using the svd formula
np.dot(U,np.dot(S,VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])